---
- name: install /etc/environment
  when: proxy_env.http_proxy is defined
  template: >
    owner=root
    group=root
    mode=644
    src='etc/environment.j2'
    dest='/etc/environment'

- name: bash consumes /etc/environment by default
  when: proxy_env.http_proxy is defined
  copy: >
    owner=root
    group=root
    src='etc/profile.d/proxyenv.sh'
    dest='/etc/profile.d/proxyenv.sh'
    mode=644

- name: YUM proxify...
  when: proxy_env.http_proxy is defined and ansible_os_family == 'RedHat' and ansible_os_distribution != 'Fedora'
  include: yum.yml

- name: DNF proxify...
  when: proxy_env.http_proxy is defined and ansible_os_distribution == 'Fedora'
  include: dnf.yml
  
- name: apt proxify
  when: proxy_env.http_proxy is defined and ansible_os_family == 'Debian'
  include: apt.yml
