---
- name: install /etc/environment
  become : yes
  become_user: root
  when: proxy_env.http_proxy is defined
  with_items:
    - environment
    - wgetrc
    - profile.d/proxyenv.sh
  template: >
    owner=root
    group=root
    mode=0644
    src=etc/{{item}}.j2
    dest=/etc/{{item}}

- name: YUM proxify...
  become : yes
  become_user: root
  when: >-
    (proxy_env.http_proxy is defined)
    and (ansible_os_family == 'RedHat')
    and (ansible_distribution != 'Fedora')
  include: yum.yml

- name: DNF proxify...
  become : yes
  become_user: root
  when: >-
    (proxy_env.http_proxy is defined)
    and (ansible_distribution == 'Fedora')
  include: dnf.yml
  
- name: apt proxify
  become : yes
  become_user: root
  when: >-
    (proxy_env.http_proxy is defined)
    and ansible_os_family == 'Debian'
  include: apt.yml
